server:
  port: 8080

spring:
  application:
    name: spring-boot-demo
  
  # Database Configuration
  datasource:
    # H2 Database (Development)
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
    # MySQL Database (Production) - Uncomment for production
    # url: jdbc:mysql://localhost:3306/spring_boot_demo?useSSL=false&serverTimezone=UTC
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root
    # password: your_password

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
